# Generated by Django 2.0.2 on 2018-02-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_agregator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsslinks',
            name='news_link_id',
        ),
        migrations.DeleteModel(
            name='NewsItems',
        ),
        migrations.DeleteModel(
            name='RssLinks',
        ),
    ]
